#!/usr/bin/env sh

set -eu

dir=$(pwd)

error() {
    echo "Error: $1" 1>&2
}

usage() {
    echo "Usage: $0 [-h|--help] [-V|--save-visualization] [EXAMPLE_DIR]"
}

java_pkg="tree-sitter-java@0.19.1"
java_dir="$dir/.$java_pkg"
if [ ! -e "$java_dir" ]; then
    echo "Missing tree-sitter Java grammar. Run bootstrap script to install."
    exit 1
fi

tssg_opts="--output-mode=always"
example_dir="."
while [ $# -gt 0 ]; do
    arg="$1"
    shift 1
    case "$arg" in
        -h|--help)
            usage
            exit 0
            ;;
        -V|--save-visualization)
            tssg_opts="$tssg_opts -V=%r/%d/%n.html"
            ;;
        *)
            example_dir="$arg"
            if [ $# -gt 0 ]; then
                error "Too many positional arguments provided."
                usage 1>&2
                exit 1
            fi
            ;;
    esac
done

tsg_file="src/stack-graphs.tsg"
tests_dir="test"
if [ ! -e "$tsg_file" ]; then
    error "Missing TSG file $tsg_file. Is $example_dir not an example directory?"
    exit 1
fi
if [ ! -e "$tests_dir" ]; then
    error "Missing directory $tests_dir. Is $example_dir not an example directory?"
    exit 1
fi

cargo -q run --manifest-path ../../tree-sitter-stack-graphs/Cargo.toml --features=cli -- test $tssg_opts --grammar "$java_dir" --tsg "$tsg_file" "$tests_dir"
