#!/bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
# Copyright © 2021, stack-graphs authors.
# Licensed under either of Apache License, Version 2.0, or MIT license, at your
# option.  Please see the LICENSE-APACHE or LICENSE-MIT files in this
# distribution for license details.
# ------------------------------------------------------------------------------

set -eu
cd "$(dirname "$0")/.."

cargo install --quiet --root . --version "^0.23" cbindgen

bin/cbindgen -o stack-graphs/include/stack-graphs.h stack-graphs
