#!/usr/bin/env bash

set -eu

cargo run --bin tree-sitter-stack-graphs --features cli -- init \
  --language-name InitTest \
  --language-id init_test \
  --language-file-extension it \
  --grammar-crate-name tree-sitter-python \
  --grammar-crate-version 0.23.2 \
  --internal \
  --non-interactive

cargo check -p tree-sitter-stack-graphs-init_test --all-features

cargo test -p tree-sitter-stack-graphs-init_test

cargo run -p tree-sitter-stack-graphs-init_test --features cli -- -V
